### ISSUE TITLE
Just saw this repositories

### ISSUE THREAD

**Issue by wetor** [uyjulian/onscripter-switch#3]
If you want to continue to improve, you can see my repositories 
https://github.com/wetor/ONScripter-jh-Switch
I'm looking forward to your kirikiroid2

**Comment by uyjulian** [comment]
Ah, thanks for letting me know.  
My kirikiroid2 port is working, but will be missing some features since zeas2 did not provide complete source code. Thankfully, Switchroot Android has made some large advancements, so the existing version could always be run there.
